---
name: hoarder

services:
  sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .sidecar
    hostname: hoarder
    env_file: ../prime/.tailscale.env
    environment:
      - TS_SERVE_PORT=3000

  service:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: always
    volumes:
      - data:/data
    network_mode: service:sidecar
    env_file:
      - .hoarder-env
    environment:
      MEILI_ADDR: http://localhost:7700
      BROWSER_WEB_URL: http://localhost:9222
      # OPENAI_API_KEY: ...
      DATA_DIR: /data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: always
    network_mode: service:sidecar
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: always
    network_mode: service:sidecar
    env_file:
      - .hoarder-env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data

volumes:
  meilisearch:
  data:
  tailscale-data:
