services:
  sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .sidecar
    env_file: ../blob/.tailscale.env
    hostname: loki
    volumes:
      - tailscale-data:/var/lib/tailscale
    environment:
      - TS_SERVE_PORT=3100

  loki:
    image: grafana/loki:latest
    network_mode: "service:sidecar"
    restart: always
    # command:
    #   - "-config.file=/etc/loki-2/local-config.yaml"
    volumes:
      - config:/etc/loki/
      - storage:/loki/

  shell:
    image: busybox:latest
    volumes:
      - config:/etc/loki/
    command: "true"

volumes:
  config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /volume1/config/loki

  storage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /volume1/Backups/loki-data
  tailscale-data:
