services:
  sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .sidecar
    env_file: ../blob/.tailscale.env
    hostname: loki
    volumes:
      - tailscale-data:/var/lib/tailscale
    environment:
      - TS_SERVE_PORT=3100

  loki:
    image: grafana/loki:latest
    network_mode: "service:sidecar"
    restart: always
    user: "1026:100"
    volumes:
      - /volume1/config/loki:/etc/loki
      - storage:/loki

volumes:
  storage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /volume1/Backups/loki-data
  tailscale-data:
