configs:
  ts-serve:
    content: |
      {"TCP":{"443":{"HTTPS":true},"80":{"HTTP":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:3100"}}},
          "$${TS_CERT_DOMAIN}:80":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:3100"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

services:
  sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .simple-sidecar
    hostname: loki

  loki:
    image: grafana/loki:latest
    network_mode: "service:sidecar"
    restart: always
    # command:
    #   - "-config.file=/etc/loki-2/local-config.yaml"
    volumes:
      - config:/etc/loki/
      - storage:/loki/

  shell:
    image: busybox:latest
    volumes:
      - config:/etc/loki/
    command: "true"

volumes:
  config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /volume1/config/loki

  storage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /volume1/Backups/loki-data
  tailscale-data:
