configs:
  ts-serve:
    content: |
      {"TCP":{"443":{"HTTPS":true},"80":{"HTTP":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:8080"}}},
          "$${TS_CERT_DOMAIN}:80":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:8080"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

services:
  sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .simple-sidecar
    hostname: yacreader

  service:
    image: yacreader/yacreaderlibraryserver:latest
    network_mode: "service:sidecar"
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - /volume1/config/yacreader:/config
      - /volume1/Media/ebooks/Comics:/comics
    restart: unless-stopped

volumes:
  tailscale-data:
