services:
  sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .sidecar
    env_file: ../blob/.tailscale.env
    hostname: yacreader
    environment:
      TS_SERVE_PORT: 8080

  service:
    image: yacreader/yacreaderlibraryserver:latest
    network_mode: "service:sidecar"
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - /volume1/config/yacreader:/config
      - /volume1/Media/ebooks/Comics:/comics
    restart: unless-stopped

volumes:
  tailscale-data:
