---
version: "3.7"
services:
  sidecar:
    hostname: udm-poller
    volumes:
      - tailscale-data:/var/lib/tailscale
    devices:
      - /dev/net/tun
    cap_add: # Required for tailscale to work
      - net_admin
      - sys_module
    env_file: .proxy.env
    environment:
      - TS_SERVE_PORT=9130
    image: ghcr.io/offbyone/sidecar:main

  udm-poller:
    image: "ghcr.io/unpoller/unpoller:${POLLER_TAG}"
    network_mode: "service:sidecar"
    restart: unless-stopped
    volumes:
      - /etc/unpoller:/etc/unpoller
    environment:
      - UP_UNIFI_DEFAULT_USER=${UNIFI_USER}
      - UP_UNIFI_DEFAULT_PASS=${UNIFI_PASS}
      - UP_UNIFI_DEFAULT_URL=${UNIFI_URL}
      - UP_POLLER_DEBUG=${POLLER_DEBUG}
      - UP_UNIFI_DEFAULT_SAVE_DPI=${POLLER_SAVE_DPI}

volumes:
  tailscale-data:
