---
services:
  sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .sidecar
    env_file: ../.tailscale.exporter.env
    hostname: udm-poller
    environment:
      - TS_SERVE_PORT=9130

  udm-poller:
    image: "ghcr.io/unpoller/unpoller:${POLLER_TAG}"
    network_mode: "service:sidecar"
    restart: unless-stopped
    volumes:
      - /etc/unpoller:/etc/unpoller
    environment:
      - UP_UNIFI_DEFAULT_USER=${UNIFI_USER}
      - UP_UNIFI_DEFAULT_PASS=${UNIFI_PASS}
      - UP_UNIFI_DEFAULT_URL=${UNIFI_URL}
      - UP_POLLER_DEBUG=${POLLER_DEBUG}
      - UP_UNIFI_DEFAULT_SAVE_DPI=${POLLER_SAVE_DPI}

volumes:
  tailscale-data:
