# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/sickchill" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/sickchill"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/sidecar"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
