services:
  sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .sidecar
    hostname: id
    env_file: ../bitbucket/.tailscale.env
    environment:
      - TS_SERVE_PORT=3080

  pocket-id:
    image: ghcr.io/pocket-id/pocket-id
    restart: unless-stopped
    env_file: .env
    network_mode: service:sidecar
    volumes:
      - "./data:/app/backend/data"
    # Optional healthcheck
    healthcheck:
      test: "curl -f http://localhost:3080/health"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    environment:
      - CADDY_PORT=3080

volumes:
  tailscale-data:
