services:
  sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .sidecar
    hostname: id
    env_file: ../bitbucket/.tailscale.env
    environment:
      - TS_SERVE_PORT=80

  pocket-id:
    image: ghcr.io/pocket-id/pocket-id
    restart: unless-stopped
    env_file: .env
    ports:
      - 80
    volumes:
      - "./data:/app/backend/data"
    # Optional healthcheck
    healthcheck:
      test: "curl -f http://localhost/health"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

volumes:
  tailscale-data:
