---
services:
  sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .sidecar
    env_file: ../bitbucket/.tailscale.env
    hostname: readarr
    environment:
      - TS_SERVE_PORT=8787

  service:
    image: lscr.io/linuxserver/readarr:develop
    environment:
      - TZ=Etc/UTC
    volumes:
      - /etc/readarr/:/config
      - blob-media:/books
    network_mode: "service:sidecar"
    restart: always

  exporter:
    image: ghcr.io/onedr0p/exportarr:latest
    command: readarr
    restart: always
    network_mode: "service:sidecar"
    environment:
      - PORT=9707
      - URL=http://localhost:8787
    # APIKEY must be set in here
    env_file: .exportarr.env

volumes:
  tailscale-data:
  blob-media:
    driver: local
    driver_opts:
      type: cifs
      device: //blob.lan.offby1.net/Media/ebooks/library
      o: username=${BLOB_USERNAME},password=${BLOB_PASSWORD},file_mode=0777,dir_mode=0777,addr=192.168.5.184
