---
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "service:sidecar-dozzle"
  sidecar-dozzle:
    hostname: dozzle-bitbucket
    restart: always
    volumes:
      - tailscale-data-dozzle:/var/lib/tailscale
    devices:
      - /dev/net/tun
    cap_add: # Required for tailscale to work
      - net_admin
      - sys_module
    env_file: .proxy.env
    environment:
      - TS_SERVE_PORT=8080
    image: ghcr.io/offbyone/sidecar:main
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
