configs:
  ts-serve:
    content: |
      {"TCP":{"443":{"HTTPS":true},"80":{"HTTP":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:13378"}}},
          "$${TS_CERT_DOMAIN}:80":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:13378"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

services:
  sidecar:
    restart: unless-stopped
    extends:
      file: ../sidecar-compose.yaml
      service: .simple-sidecar
    hostname: audiobookshelf
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    network_mode: service:sidecar
    volumes:
      - /mnt/media/audio/books:/audiobooks
      - /mnt/media/audio/podcasts:/podcasts
      - /etc/audiobookshelf:/config
      - /var/lib/audiobookshelf:/metadata
    environment:
      - TZ=America/Los_Angeles
      - PORT=13378
    restart: always

volumes:
  tailscale-data:
