---
version: "3.3"
services:
  sidecar:
    hostname: sickchill
    volumes:
      - tailscale-data:/var/lib/tailscale
    devices:
      - /dev/net/tun
    cap_add: # Required for tailscale to work
      - net_admin
      - sys_module
    env_file: .proxy.env
    environment:
      - TS_SERVE_PORT=8080
    image: ghcr.io/offbyone/sidecar:main
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  sickchill:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ghcr.io/offbyone/sickchill:main
    volumes:
      - blob-media:/mnt/media
      - sickchill-data:/var/lib/sickchill
    network_mode: "service:sidecar"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  tailscale-data:
  blob-media:
    driver: local
    driver_opts:
      type: cifs
      device: //blob.lan.offby1.net/Media
      o: username=${BLOB_USERNAME},password=${BLOB_PASSWORD},file_mode=0777,dir_mode=0777,addr=192.168.1.10
  sickchill-data:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/sickchill
      o: bind
