version: '3.5'

services:
  cobalt-api:
    image: ghcr.io/wukko/cobalt:7
    restart: unless-stopped
    container_name: cobalt-api

    init: true

    # if container doesn't run detached on your machine, uncomment the next line:
    #tty: true

    ports:
      - 9000:9000/tcp
      # if you're using a reverse proxy, uncomment the next line:
      #- 127.0.0.1:9000:9000

    environment:
      # replace apiURL with your instance's target url in same format
      - apiURL=https://co.wuk.sh/
      # replace apiName with your instance's distinctive name
      - apiName=eu-nl
      # if you want to use cookies when fetching data from services, uncomment the next line
      #- cookiePath=/cookies.json
      # see cookies_example.json for example file.
    labels:
      - com.centurylinklabs.watchtower.scope=cobalt

      # if you want to use cookies when fetching data from services, uncomment volumes and next line
      #volumes:
      #- ./cookies.json:/cookies.json

  cobalt-web:
    image: ghcr.io/wukko/cobalt:7
    restart: unless-stopped
    container_name: cobalt-web

    init: true

    # if container doesn't run detached on your machine, uncomment the next line:
    #tty: true

    ports:
      - 9001:9001/tcp
      # if you're using a reverse proxy, uncomment the next line:
      #- 127.0.0.1:9001:9001

    environment:
      # replace webURL with your instance's target url in same format
      - webURL=https://cobalt.tools/
      # replace apiURL with preferred api instance url
      - apiURL=https://co.wuk.sh/

    labels:
      - com.centurylinklabs.watchtower.scope=cobalt

    # update the cobalt image automatically with watchtower
  watchtower:
    image: ghcr.io/containrrr/watchtower
    restart: unless-stopped
    command: --cleanup --scope cobalt --interval 900
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
