services:
  sidecar:
    hostname: cobalt
    volumes:
      - tailscale-data:/var/lib/tailscale
    devices:
      - /dev/net/tun
    cap_add: # Required for tailscale to work
      - net_admin
      - sys_module
    env_file: ../bitbucket/.tailscale.env
    # not serving using the sidecar herlper, run ./setup-serve.sh instead
    # environment:
    #   - TS_SERVE_PORT=9001
    image: ghcr.io/offbyone/sidecar:main
    labels:
      - com.centurylinklabs.watchtower.scope=cobalt
      - "com.centurylinklabs.watchtower.enable=true"

  cobalt-api:
    image: ghcr.io/wukko/cobalt:7
    restart: always
    container_name: cobalt-api
    network_mode: service:sidecar

    init: true

    # if container doesn't run detached on your machine, uncomment the next line:
    #tty: true

    # ports:
    #   - 9000:9000/tcp
    #   # if you're using a reverse proxy, uncomment the next line:
    #   #- 127.0.0.1:9000:9000

    environment:
      # replace apiURL with your instance's target url in same format
      - apiURL=https://cobalt.camel-tortoise.ts.net/
      # replace apiName with your instance's distinctive name
      - apiName=cobalt-tailnet
      # if you want to use cookies when fetching data from services, uncomment the next line
      #- cookiePath=/cookies.json
      # see cookies_example.json for example file.
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.centurylinklabs.watchtower.scope=cobalt

      # if you want to use cookies when fetching data from services, uncomment volumes and next line
    volumes:
      - ./cookies.json:/cookies.json

  cobalt-web:
    image: ghcr.io/wukko/cobalt:7
    restart: always
    container_name: cobalt-web
    network_mode: service:sidecar

    init: true

    # if container doesn't run detached on your machine, uncomment the next line:
    #tty: true

    # ports:
    #   - 9001:9001/tcp
    #   # if you're using a reverse proxy, uncomment the next line:
    #   #- 127.0.0.1:9001:9001

    environment:
      # replace webURL with your instance's target url in same format
      - webURL=https://cobalt.camel-tortoise.ts.net/web/
      # replace apiURL with preferred api instance url
      - apiURL=https://cobalt.camel-tortoise.ts.net/

    labels:
      - com.centurylinklabs.watchtower.scope=cobalt
      - com.centurylinklabs.watchtower.enable=true

volumes:
  tailscale-data:
