services:
  sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .sidecar
    env_file: ../blob/.tailscale.env
    hostname: logs
    volumes:
      - tailscale-data:/var/lib/tailscale
    environment:
      - TS_SERVE_PORT=3100

  victoria-logs:
    image: docker.io/victoriametrics/victoria-logs:v1.0.0-victorialogs
    network_mode: service:sidecar
    restart: always
    command:
      - -journald.streamFields=_STREAM_ID,_SYSTEMD_UNIT,_HOSTNAME
      - -retention.maxDiskSpaceUsageBytes=1TiB
      - -retentionPeriod=1y
    ports:
      - "9428:9428"
    volumes:
      - /volume1/Backups/victoria-logs-data:/victoria-logs-data

volumes:
  tailscale-data:
