configs:
  ts-serve:
    content: |
      {"TCP":{"443":{"HTTPS":true},"80":{"HTTP":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:9428"}}},
          "$${TS_CERT_DOMAIN}:80":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:9428"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

services:
  sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .simple-sidecar
    hostname: logs

  victoria-logs:
    image: docker.io/victoriametrics/victoria-logs:v1.23.3-victorialogs
    network_mode: service:sidecar
    restart: always
    command:
      - -journald.streamFields=_STREAM_ID,_SYSTEMD_UNIT,_HOSTNAME
      - -retention.maxDiskSpaceUsageBytes=1TiB
      - -retentionPeriod=1y
    volumes:
      - /volume1/Backups/victoria-logs-data:/victoria-logs-data

volumes:
  tailscale-data:
