configs:
  ts-serve:
    content: |
      {"TCP":{"443":{"HTTPS":true},"80":{"HTTP":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:8080"}}},
          "$${TS_CERT_DOMAIN}:80":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:8080"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

services:
  sidecar:
    restart: unless-stopped
    extends:
      file: ../sidecar-compose.yaml
      service: .simple-sidecar
    hostname: miniflux
  miniflux:
    image: miniflux/miniflux:latest
    network_mode: service:sidecar
    labels:
      LOG_EXPORT: "1"
    logging:
      driver: journald
      options:
        tag: "{{.Name}}"
        labels: LOG_EXPORT
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.local
    secrets:
      - oauth2_client_id
      - oauth2_client_secret
    environment:
      - DISABLE_LOCAL_AUTH=1
      - OAUTH2_CLIENT_ID_FILE=/run/secrets/oauth2_client_id
      - OAUTH2_CLIENT_SECRET_FILE=/run/secrets/oauth2_client_secret
      - OAUTH2_OIDC_DISCOVERY_ENDPOINT=https://id.offby1.net
      - OAUTH2_PROVIDER=oidc
      - OAUTH2_REDIRECT_URL=https://miniflux.camel-tortoise.ts.net/oauth2/oidc/callback
      - INTEGRATION_ALLOW_PRIVATE_NETWORKS=1
      - LOG_FORMAT=json
      - METRICS_ALLOWED_NETWORKS=100.64.0.0/10
      - METRICS_COLLECTOR=1
      - POLLING_FREQUENCY=30
      - RUN_MIGRATIONS=1
  db:
    image: postgres:17-alpine
    network_mode: service:sidecar
    env_file:
      - .env.local
    environment:
      - POSTGRES_DB=miniflux
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
volumes:
  miniflux-db:
  tailscale-data:
secrets:
  oauth2_client_id:
    file: ./oauth2_client_id.txt
  oauth2_client_secret:
    file: ./oauth2_client_secret.txt
