---
name: bichon

configs:
  ts-serve:
    content: |
      {"TCP":{"443":{"HTTPS":true},"80":{"HTTP":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:15630"}}},
          "$${TS_CERT_DOMAIN}:80":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:15630"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

services:
  sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .simple-sidecar
    hostname: bichon

  bichon:
    image: rustmailer/bichon:latest
    restart: always
    network_mode: service:sidecar
    container_name: bichon
    working_dir: /data
    environment:
      - BICHON_LOG_LEVEL=info
      - BICHON_ROOT_DIR=/data
    healthcheck:
      test:
        ["CMD-SHELL", "curl -fs http://localhost:15630/api/status || exit 1"]
      interval: 30s
      timeout: 5s
      start_period: 5s
      retries: 3
    volumes:
      - data:/data

volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /volume1/Backups/email
  tailscale-data:
