---
services:
  sidecar-blob:
    extends:
      file: ../sidecar-compose.yaml
      service: .sidecar
    hostname: syncthing-exporter-blob
    env_file: ../.tailscale.exporter.env
    environment:
      - TS_SERVE_PORT=9093

  exporter-blob:
    restart: always
    environment:
      SYNCTHING_URI: "http://blob:8384/"
      SYNCTHING_TOKEN: "${BLOB_SYNCTHING_TOKEN}"
    network_mode: "service:sidecar-blob"
    image: f100024/syncthing_exporter:latest

  sidecar-whatbox:
    extends:
      file: ../sidecar-compose.yaml
      service: .sidecar
    hostname: syncthing-exporter-whatbox
    env_file: ../.tailscale.exporter.env
    environment:
      - TS_SERVE_PORT=9093

  exporter-whatbox:
    restart: always
    environment:
      SYNCTHING_URI: "https://syncthing-whatbox.camel-tortoise.ts.net/"
      SYNCTHING_TOKEN: "${WHATBOX_SYNCTHING_TOKEN}"
    network_mode: "service:sidecar-whatbox"
    image: f100024/syncthing_exporter:latest

secrets:
  blob-token:
    file: blob-token.txt
  whatbox-token:
    file: whatbox-token.txt
volumes:
  tailscale-data-blob:
  tailscale-data-whatbox:
