configs:
  ts-serve:
    content: |
      {"TCP":{"443":{"HTTPS":true},"80":{"HTTP":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:10416"}}},
          "$${TS_CERT_DOMAIN}:80":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:10416"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

services:
  sidecar:
    restart: unless-stopped
    extends:
      file: ../sidecar-compose.yaml
      service: .simple-sidecar
    hostname: breezewiki

  breezewiki:
    container_name: breezewiki
    image: ghcr.io/offbyone/breezewiki:main
    restart: unless-stopped
    network_mode: service:sidecar
    volumes:
      - "./config.ini:/app/config.ini"

volumes:
  tailscale-data:
