---
configs:
  ts-serve:
    content: ""
    # content: |
    #   {"TCP":{"443":{"HTTPS":true},"80":{"HTTP":true}},
    #   "Web":{"$${TS_CERT_DOMAIN}:443":
    #       {"Handlers":{"/":
    #       {"Proxy":"http://127.0.0.1:9090"}}},
    #       "$${TS_CERT_DOMAIN}:80":
    #       {"Handlers":{"/":
    #       {"Proxy":"http://127.0.0.1:9090"}}}},
    #   "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

services:
  sidecar:
    restart: unless-stopped
    extends:
      file: ../sidecar-compose.yaml
      service: .sidecar-noserve
    hostname: blob-postgres

  postgresql:
    image: "postgres:17"
    restart: always
    network_mode: "service:sidecar"
    user: postgres
    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - data:/var/lib/postgresql/data
      - config:/etc/postgresql
      - logs:/var/log/postgresql

volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /volume1/postgres/data
  config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /volume1/postgres/config
  logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /volume1/postgres/logs

  tailscale-data:
