---
version: "3.4"
services:
  sidecar:
    hostname: radarr
    volumes:
      - tailscale-data:/var/lib/tailscale
    devices:
      - /dev/net/tun
    cap_add: # Required for tailscale to work
      - net_admin
      - sys_module
    env_file: .proxy.env
    environment:
      - TS_SERVE_PORT=8310
    image: ghcr.io/offbyone/sidecar:main
  radarr:
    image: lscr.io/linuxserver/radarr:4.6.4.7568-ls178
    network_mode: "service:sidecar"
    restart: unless-stopped
    volumes:
      - blob-media:/media
      - radarr-config:/config
    environment:
      - PGID=1000
      - PUID=1000
  exporter:
    image: ghcr.io/onedr0p/exportarr:latest
    command: radarr
    restart: unless-stopped
    network_mode: "service:sidecar"
    environment:
      - PORT=9707
      - URL=http://localhost:8310
    # APIKEY must be set in here
    env_file: .exportarr.env

volumes:
  tailscale-data:
  blob-media:
    driver: local
    driver_opts:
      type: cifs
      device: //blob.lan.offby1.net/Media
      o: username=${BLOB_USERNAME},password=${BLOB_PASSWORD},file_mode=0777,dir_mode=0777,addr=192.168.1.10
  radarr-config:
    driver: local
    driver_opts:
      type: cifs
      device: //blob.lan.offby1.net/config/radarr/
      o: username=${BLOB_USERNAME},password=${BLOB_PASSWORD},file_mode=0777,dir_mode=0777,addr=192.168.1.10
