---
services:
  sidecar:
    extends:
      file: ../../sidecar-compose.yaml
      service: .sidecar
    hostname: plex-exporter
    env_file: ../.tailscale.exporter.env
    environment:
      - TS_SERVE_PORT=9000

  plex-exporter:
    image: "ghcr.io/jsclayton/prometheus-plex-exporter"
    # image: "ghcr.io/axsuul/plex-media-server-exporter:${PLEX_EXPORTER_POLLER_TAG}"
    network_mode: "service:sidecar"
    restart: always
    environment:
      - PLEX_TOKEN=${PLEX_TOKEN}
      - PLEX_ADDR=${PLEX_ADDR}
      - PLEX_SERVER=${PLEX_ADDR}

volumes:
  tailscale-data:
