version: "3.5"

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.links/watchtower-config.json:/config.json
    command: --interval 30
    env_file: .env
    environment:
      - "WATCHTOWER_LABEL_ENABLE=true"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
