---
services:
  sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .sidecar
    hostname: blackbox-exporter
    env_file: ../.tailscale.exporter.env
    environment:
      - TS_SERVE_PORT=9115

  blackbox-exporter:
    network_mode: "service:sidecar"
    image: quay.io/prometheus/blackbox-exporter:latest
    restart: always
    volumes:
      - "${BLACKBOX_CONFIG_BASE}:/config"
    command:
      - "--config.file=/config/blackbox.yml"
      - "--web.listen-address=0.0.0.0:9115"

volumes:
  tailscale-data:
