---
version: "3.7"
services:
  sidecar:
    hostname: blackbox-exporter
    volumes:
      - tailscale-data:/var/lib/tailscale
    devices:
      - /dev/net/tun
    cap_add: # Required for tailscale to work
      - net_admin
      - sys_module
    env_file: ../.tailscale.exporter.env
    environment:
      - TS_SERVE_PORT=9115
    image: ghcr.io/offbyone/sidecar:main

  blackbox-exporter:
    network_mode: "service:sidecar"
    image: quay.io/prometheus/blackbox-exporter:latest
    restart: always
    volumes:
      - "${BLACKBOX_CONFIG_BASE}:/config"
    command:
      - "--config.file=/config/blackbox.yml"
      - "--web.listen-address=0.0.0.0:9115"

volumes:
  tailscale-data:
