---
configs:
  ts-serve:
    content: |
      {"TCP":{"443":{"HTTPS":true},"80":{"HTTP":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:9115"}}},
          "$${TS_CERT_DOMAIN}:80":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:9115"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

services:
  sidecar:
    extends:
      file: ../../sidecar-compose.yaml
      service: .simple-sidecar
    hostname: blackbox-exporter

  blackbox-exporter:
    network_mode: "service:sidecar"
    image: quay.io/prometheus/blackbox-exporter:latest
    restart: always
    volumes:
      - "${BLACKBOX_CONFIG_BASE}:/config"
    command:
      - "--config.file=/config/blackbox.yml"
      - "--web.listen-address=0.0.0.0:9115"

volumes:
  tailscale-data:
