---
version: "3.4"
services:
  sidecar:
    hostname: atuin
    restart: always
    volumes:
      - tailscale-data:/var/lib/tailscale
    devices:
      - /dev/net/tun
    cap_add: # Required for tailscale to work
      - net_admin
      - sys_module
    env_file: ../bitbucket/.tailscale.env
    environment:
      - TS_SERVE_PORT=8888
    image: ghcr.io/offbyone/sidecar:main
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  atuin:
    image: ghcr.io/atuinsh/atuin:18.3.0
    network_mode: "service:sidecar"
    restart: always
    depends_on:
      - db
    command: server start
    volumes:
      - atuin-config:/config
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "true"
      ATUIN_DB_URI: postgres://$ATUIN_DB_USERNAME:$ATUIN_DB_PASSWORD@localhost/atuin
  db:
    image: postgres:14
    restart: always
    network_mode: "service:sidecar"
    volumes: # Don't remove permanent storage for index database files!
      - "atuin-data:/var/lib/postgresql/data/"
    environment:
      POSTGRES_USER: $ATUIN_DB_USERNAME
      POSTGRES_PASSWORD: $ATUIN_DB_PASSWORD
      POSTGRES_DB: atuin

volumes:
  tailscale-data:
  atuin-data:
  atuin-config:
    driver: local
    driver_opts:
      type: cifs
      device: //blob.lan.offby1.net/config/atuin/
      o: username=${BLOB_USERNAME},password=${BLOB_PASSWORD},file_mode=0777,dir_mode=0777,addr=192.168.5.184
