---
version: "3.4"
services:
  sidecar:
    hostname: jackett
    volumes:
      - tailscale-data:/var/lib/tailscale
    devices:
      - /dev/net/tun
    cap_add: # Required for tailscale to work
      - net_admin
      - sys_module
    env_file: .proxy.env
    environment:
      - TS_SERVE_PORT=9117
    image: ghcr.io/offbyone/sidecar:latest
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    network_mode: "service:sidecar"
    restart: unless-stopped
    volumes:
      - blob-media:/media
      - jackett-config:/config
    environment:
      - PGID=1000
      - PUID=1000

volumes:
  tailscale-data:
  blob-media:
    driver: local
    driver_opts:
      type: cifs
      device: //blob.lan.offby1.net/Media
      o: username=${BLOB_USERNAME},password=${BLOB_PASSWORD},file_mode=0777,dir_mode=0777,addr=192.168.1.10
  jackett-config:
    driver: local
    driver_opts:
      type: none
      device: /etc/jackett
      o: bind
