---
services:
  sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .sidecar
    env_file: ../bitbucket/.tailscale.env
    hostname: jackett
    environment:
      - TS_SERVE_PORT=9117

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    network_mode: "service:sidecar"
    restart: always
    volumes:
      - blob-media:/media
      - jackett-config:/config
    environment:
      - PGID=1000
      - PUID=1000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  tailscale-data:
  blob-media:
    driver: local
    driver_opts:
      type: cifs
      device: //blob.lan.offby1.net/Media
      o: username=${BLOB_USERNAME},password=${BLOB_PASSWORD},file_mode=0777,dir_mode=0777,addr=192.168.5.184
  jackett-config:
    driver: local
    driver_opts:
      type: none
      device: /etc/jackett
      o: bind
