---
- name: Verify service definitions exist
  ansible.builtin.stat:
    path: "{{ repo_path }}/{{ item.path | default(item.name) }}/{{ item.compose_file | default('compose.yml') }}"
  loop: "{{ services }}"
  register: service_files

- name: Fail if any service definition doesn't exist
  ansible.builtin.fail:
    msg: "Service definition {{ item.item.name }} not found at {{ repo_path }}/{{ item.item.path | default(item.item.name) }}/{{ item.item.compose_file | default('compose.yml') }}"
  when: not item.stat.exists
  loop: "{{ service_files.results }}"

- name: Deploy and ensure services are up
  community.docker.docker_compose_v2:
    wait: true
    project_src: "{{ repo_path }}/{{ item.path | default(item.name) }}"
    files:
      - "{{ item.compose_file | default('compose.yml') }}"
    state: present
    remove_orphans: true
  loop: "{{ services }}"
  register: compose_result
  become: "{{ become_for_docker }}"
