configs:
  ts-serve:
    content: |
      {"TCP":{"443":{"HTTPS":true},"80":{"HTTP":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:8000"}}},
          "$${TS_CERT_DOMAIN}:80":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:8000"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

services:
  sidecar:
    restart: unless-stopped
    extends:
      file: ../sidecar-compose.yaml
      service: .simple-sidecar
    hostname: yt-dlp-co2
  service:
    image: carbonatedwaterorg/yt-dlp-co2:latest
    network_mode: service:sidecar
    volumes:
      - /volume1/Media/video/yt-dlp/:/app/downloads

volumes:
  tailscale-data:
