---
services:
  sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .sidecar
    env_file: ../bitbucket/.tailscale.env
    hostname: logs
    environment:
      - TS_SERVE_PORT=5080

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    network_mode: "service:sidecar"
    restart: always
    env_file: .env.local
    volumes:
      - data:/data
volumes:
  tailscale-data:
  data:
