---
version: "3.4"
services:
  sidecar:
    hostname: logs
    restart: always
    volumes:
      - tailscale-data:/var/lib/tailscale
    devices:
      - /dev/net/tun
    cap_add: # Required for tailscale to work
      - net_admin
      - sys_module
    env_file: ../bitbucket/.tailscale.env
    environment:
      - TS_SERVE_PORT=5080
    image: ghcr.io/offbyone/sidecar:main

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    network_mode: "service:sidecar"
    restart: always
    env_file: .logs.env
    volumes:
      - data:/data
volumes:
  tailscale-data:
  data:
