---
version: "3.4"
services:
  sidecar:
    hostname: lidarr
    volumes:
      - tailscale-data:/var/lib/tailscale
    devices:
      - /dev/net/tun
    cap_add: # Required for tailscale to work
      - net_admin
      - sys_module
    env_file: .proxy.env
    environment:
      - TS_SERVE_PORT=8686
    image: ghcr.io/offbyone/sidecar:main

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - lidarr-config:/config
      - blob-media:/data
    network_mode: "service:sidecar"
    restart: unless-stopped
  exporter:
    image: ghcr.io/onedr0p/exportarr:latest
    command: lidarr
    restart: unless-stopped
    network_mode: "service:sidecar"
    environment:
      - PORT=9707
      - URL=http://localhost:8686
    # APIKEY must be set in here
    env_file: .exportarr.env

  exporter:
    image: ghcr.io/onedr0p/exportarr:latest
    command: lidarr
    restart: unless-stopped
    environment:
      - PORT=9707
      - URL=http://localhost:8686
    # APIKEY must be set in here
    env_file: .exportarr.env

volumes:
  tailscale-data:
  blob-media:
    driver: local
    driver_opts:
      type: cifs
      device: //blob.lan.offby1.net/Media
      o: username=${BLOB_USERNAME},password=${BLOB_PASSWORD},file_mode=0777,dir_mode=0777,addr=192.168.1.10
  lidarr-config:
    driver: local
    driver_opts:
      type: none
      device: /etc/lidarr
      o: bind
