services:
  - name: atuin
    compose_file: docker-compose.yml
  - name: calibre-web
    compose_file: compose.yml
  - name: breezewiki
    compose_file: compose.yaml
  - name: changedetection
    compose_file: docker-compose.yml
  - name: cobalt
    compose_file: docker-compose.yml
  - name: flaresolverr
    compose_file: compose.yaml
  - name: jackett
    compose_file: docker-compose.yml
  - name: lidarr
    compose_file: docker-compose.yml
  - name: metrics
    compose_file: docker-compose.yml
  - name: metrics-blackbox-exporter
    path: metrics/blackbox-exporter
    compose_file: docker-compose.yml
  - name: metrics-plex-exporter
    path: metrics/plex-exporter
    compose_file: docker-compose.yml
  - name: metrics-snmp-exporter
    path: metrics/snmp-exporter
    compose_file: docker-compose.yml
  - name: metrics-synology-monitor
    path: metrics/synology-monitor
    compose_file: docker-compose.yml
  - name: metrics-udm-poller
    path: metrics/udm-poller
    compose_file: docker-compose.yml
  - name: miniflux
    compose_file: compose.yaml
  - name: openobserve
    compose_file: docker-compose.yml
  - name: radarr
    compose_file: docker-compose.yml
  # - name: radicale
  #   compose_file: compose.yml
  - name: readarr
    compose_file: docker-compose.yml
  - name: sonarr
    compose_file: compose.yml
  - name: tandoor
    compose_file: compose.yml
  # - name: whisparr
  #   compose_file: compose.yaml
