repo_path: "{{ ansible_user_dir }}/ops-containers"
services:
  - name: archivebox
    compose_file: docker-compose.yml
  - name: bichon
    compose_file: compose.yaml
  - name: prometheus
    compose_file: docker-compose.yml
  - name: victoria-logs
    compose_file: compose.yaml
  - name: yacreader
    compose_file: compose.yml
    up: false
  - name: sharry
    compose_file: compose.yml
  - name: minio
    compose_file: compose.yaml
    up: false
  - name: blob-postgres
    compose_file: compose.yaml
  - name: shop-prometheus
    compose_file: compose.yml

become_for_docker: true
