configs:
  ts-serve:
    content: |
      {"TCP":{"443":{"HTTPS":true},"80":{"HTTP":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:8181"}}},
          "$${TS_CERT_DOMAIN}:80":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:8181"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

services:
  sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .simple-sidecar
    hostname: issued

  service:
    image: ghcr.io/metalogico/issued:latest
    restart: unless-stopped
    network_mode: service:sidecar
    environment:
      - DATA_DIR=/app/data
    volumes:
      - /volume1/Media/ebooks/Comics:/comics:ro
      - issued_data:/app/data

volumes:
  issued_data:
  tailscale-data:
