services:
  prometheus-sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .sidecar
    env_file: ../bitbucket/.tailscale.env
    hostname: prometheus
    volumes:
      - prometheus-tailscale-data:/var/lib/tailscale
    environment:
      - TS_SERVE_PORT=9090

  prometheus:
    image: "prom/prometheus:v3.0.0"
    restart: always
    network_mode: "service:prometheus-sidecar"
    volumes:
      - /etc/prometheus:/etc/prometheus
      - prometheus-storage:/prometheus

  grafana-sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .sidecar
    # Why is this commented out? Because grafana needs to be able to access
    # the shared shop monitor endpoint. Nodes shared in from other tailnets
    # cannot be shared with tagged devices, only with owned ones. So, this
    # needs to be "owned" by my user.
    # env_file: ../bitbucket/.tailscale.env
    hostname: grafana
    volumes:
      - grafana-tailscale-data:/var/lib/tailscale
    environment:
      - TS_SERVE_PORT=3000

  grafana:
    image: "grafana/grafana:9.3.2"
    network_mode: "service:grafana-sidecar"
    restart: always
    user: "1000:1000"
    volumes:
      - /etc/grafana:/etc/grafana
      - grafana-storage:/var/lib/grafana

  loki-sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .sidecar
    env_file: ../bitbucket/.tailscale.env
    hostname: loki
    volumes:
      - loki-tailscale-data:/var/lib/tailscale
    environment:
      - TS_SERVE_PORT=3100

  loki:
    image: grafana/loki:latest
    network_mode: "service:loki-sidecar"
    restart: always
    volumes:
      - /etc/loki:/etc/loki
      - loki-storage:/loki

volumes:
  grafana-storage:
  loki-storage:
  prometheus-storage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/tick/prometheus

  prometheus-tailscale-data:
  grafana-tailscale-data:
  loki-tailscale-data:
