services:
  grafana-sidecar:
    extends:
      file: ../sidecar-compose.yaml
      service: .sidecar
    # Why is this commented out? Because grafana needs to be able to access
    # the shared shop monitor endpoint. Nodes shared in from other tailnets
    # cannot be shared with tagged devices, only with owned ones. So, this
    # needs to be "owned" by my user.
    # env_file: ../bitbucket/.tailscale.env
    hostname: grafana
    volumes:
      - grafana-tailscale-data:/var/lib/tailscale
    environment:
      - TS_SERVE_PORT=3000

  grafana:
    image: "grafana/grafana:11.3.0"
    network_mode: "service:grafana-sidecar"
    restart: always
    user: "1000:1000"
    environment:
      - GF_INSTALL_PLUGINS=https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/v0.7.0/victorialogs-datasource-v0.7.0.zip;victorialogs-datasource
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=victorialogs-datasource
    volumes:
      - /etc/grafana:/etc/grafana
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
  loki-storage:
  prometheus-storage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/tick/prometheus

  prometheus-tailscale-data:
  grafana-tailscale-data:
  loki-tailscale-data:
