up: top-up exporters-up
down: exporters-down top-down

top-up:
    docker compose up -d

top-down:
    docker compose down

exporters-up: (svc-up "blackbox-exporter") (svc-up "plex-exporter") (svc-up "snmp-exporter") (svc-up "synology-monitor") (svc-up "udm-poller")
exporters-down: (svc-down "blackbox-exporter") (svc-down "plex-exporter") (svc-down "snmp-exporter") (svc-down "synology-monitor") (svc-down "udm-poller")

svc-up name:
    cd {{ name }} && docker compose up -d

svc-down name:
    cd {{ name }} && docker compose down
